services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    ports:
      - "80:80"
    volumes:
      - /:/srv
      - database:/database
      - config:/config

volumes:
  database:
  config:
