volumes:
  forgejo_data:
    driver: local
  postgres_data:
    driver: local

services:
  db:
    image: postgres:14
    container_name: forgejo_db
    restart: always
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  forgejo:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    restart: always
    volumes:
      - ./app.ini:/etc/forgejo/app.ini
      - forgejo_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:6.0.0
    container_name: runner
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    user: 0:0
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: forgejo-runner -c config.yml daemon
